<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ZmijSharp/ZmijSharp.csproj" />
    <ProjectReference Include="../../src/UnroundedScaling.Comparison/UnroundedScaling.Comparison.csproj" />
    <ProjectReference Include="../../benchmarks/ZmijSharp.FloatFull/ZmijSharp.FloatFull.csproj" Aliases="ZmijFloatFull" />
    <ProjectReference Include="../../benchmarks/XjbSharp/XjbSharp.csproj" Aliases="XjbFull" />
    <ProjectReference Include="../../benchmarks/XjbSharp.Compact/XjbSharp.Compact.csproj" Aliases="XjbCompact" />
  </ItemGroup>
</Project>
