// <auto-generated />
// Generated by verify_and_generate.py; exact replacement for q = -293..324.
// Derived from integer interval constraints; do not hand-edit constants.
// Reconstruction follows the normalized major/minor method credited to
// Dougall Johnson in vitaut/zmij. See THIRD-PARTY-NOTICES.txt and
// docs/benchmark-results.md (size profiles and primary sources).
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace ZmijSharp;

internal static class CompactPow10Cache
{
    internal const int MinExponent = -293;
    internal const int MaxExponent = 324;
    private const int Stride = 28;

    // Call only for MinExponent <= decimalExp <= MaxExponent.
    // No heap arrays or runtime table expansion are required.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static void Get(int decimalExp, out ulong high, out ulong low)
    {
        Debug.Assert(decimalExp >= MinExponent && decimalExp <= MaxExponent);
        unchecked
        {
            int index = decimalExp - MinExponent;
            int block = index / Stride;
            int residue = index - block * Stride;
            int offset = block * 2;
            ulong m = GetMinor(residue);

            ulong lowerHigh = Math.BigMul(Anchors[offset + 1], m, out ulong c0);
            ulong upperHigh = Math.BigMul(Anchors[offset], m, out ulong upperLow);
            ulong c1 = lowerHigh + upperLow;
            ulong c2 = upperHigh + (c1 < lowerHigh ? 1UL : 0UL);

            // Normalize the 192-bit product by shifting right by 63 or 64.
            if ((c2 >> 63) != 0)
            {
                high = c2;
                low = c1;
            }
            else
            {
                high = (c2 << 1) | (c1 >> 63);
                low = (c1 << 1) | (c0 >> 63);
            }

            ulong correction = (ulong)((Fixups[index >> 3] >> (index & 7)) & 1);
            // The generator proves this correction never borrows from high
            // for any of the 618 entries. Do not extend the table unchecked.
            Debug.Assert(low >= correction);
            low -= correction;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ulong GetMinor(int residue) => Minor[residue];

    // 23 * 16 = 368 bytes, stored high word then low word.
    private static ReadOnlySpan<ulong> Anchors =>
    [
        0xCC5FC196FEFD7D0CUL, 0x1E53ED49A96272C9UL, // q0 = -293
        0xCE5D73FF402D98E3UL, 0xFB0A3D212DC81290UL, // q0 = -265
        0xD0601D8EFC57B08BUL, 0xF13B94DAF124DA27UL, // q0 = -237
        0xD267CAA862A12D66UL, 0xD072DF63C324FD7CUL, // q0 = -209
        0xD47487CC8470652BUL, 0x7647C32000696720UL, // q0 = -181
        0xD686619BA27255A2UL, 0xC80A537B0EFEFEBEUL, // q0 = -153
        0xD89D64D57A607744UL, 0xE871C7BF077BA8B8UL, // q0 = -125
        0xDAB99E59958885C4UL, 0xE95FAB368E45ECEEUL, // q0 = -97
        0xDCDB1B2798182244UL, 0xF8E431456CF88E66UL, // q0 = -69
        0xDF01E85F912E37A3UL, 0x6B6C46DEC52F6689UL, // q0 = -41
        0xE12E13424BB40E13UL, 0x2865A5F206B06FBAUL, // q0 = -13
        0xE35FA931A0000000UL, 0x0000000000000000UL, // q0 = 15
        0xE596B7B0C643C719UL, 0x6D9CCD05D0000000UL, // q0 = 43
        0xE7D34C64A9C85D44UL, 0x60DBBCA87196B617UL, // q0 = 71
        0xEA1575143CF97226UL, 0xF52D09D71A3293BEUL, // q0 = 99
        0xEC5D3FA8CE427AFFUL, 0xA3E51F138AB4CEBFUL, // q0 = 127
        0xEEAABA2E5DBF6784UL, 0x95BA2A53F983CF39UL, // q0 = 155
        0xF0FDF2D3F3C30B9FUL, 0x656D44A2A11C51D6UL, // q0 = 183
        0xF356F7EBF83552FEUL, 0x0583F6B8C4124D44UL, // q0 = 211
        0xF5B5D7EC8ACB58A2UL, 0xAE10AF696774B1DCUL, // q0 = 239
        0xF81AA16FDC1B81DAUL, 0xDD94B7868E94050BUL, // q0 = 267
        0xFA856334878FC150UL, 0xB14F98F6F0FEB952UL, // q0 = 295
        0xFCF62C1DEE382C42UL, 0x46729E03DD9ED7B5UL, // q0 = 323
    ];

    // 28 * 8 = 224 bytes; normalized exact powers of ten.
    private static ReadOnlySpan<ulong> Minor =>
    [
        0x8000000000000000UL, 0xA000000000000000UL, 0xC800000000000000UL, 0xFA00000000000000UL,
        0x9C40000000000000UL, 0xC350000000000000UL, 0xF424000000000000UL, 0x9896800000000000UL,
        0xBEBC200000000000UL, 0xEE6B280000000000UL, 0x9502F90000000000UL, 0xBA43B74000000000UL,
        0xE8D4A51000000000UL, 0x9184E72A00000000UL, 0xB5E620F480000000UL, 0xE35FA931A0000000UL,
        0x8E1BC9BF04000000UL, 0xB1A2BC2EC5000000UL, 0xDE0B6B3A76400000UL, 0x8AC7230489E80000UL,
        0xAD78EBC5AC620000UL, 0xD8D726B7177A8000UL, 0x878678326EAC9000UL, 0xA968163F0A57B400UL,
        0xD3C21BCECCEDA100UL, 0x84595161401484A0UL, 0xA56FA5B99019A5C8UL, 0xCECB8F27F4200F3AUL,
    ];

    // One correction bit per original entry: ceil(618/8) = 78 bytes.
    private static ReadOnlySpan<byte> Fixups =>
    [
        0x1F, 0x36, 0x4E, 0x3A, 0x40, 0x18, 0xB0, 0x09, 0x0E, 0x74, 0x19, 0x20,
        0x00, 0x00, 0xFF, 0xB6, 0xFB, 0x1F, 0x48, 0x9A, 0x21, 0x43, 0xAC, 0x4F,
        0x90, 0x3F, 0x88, 0x82, 0x01, 0x00, 0x00, 0x50, 0x0B, 0xF6, 0x30, 0x97,
        0x1B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0xF7, 0xCC,
        0xFD, 0x01, 0x82, 0x6A, 0xD0, 0x37, 0xCD, 0x78, 0x01, 0x24, 0x00, 0x50,
        0x0C, 0x0D, 0xA8, 0x0D, 0xE2, 0x24, 0x1C, 0x3E, 0x75, 0x78, 0x41, 0x13,
        0xB0, 0x1C, 0x00, 0x01, 0x01, 0x00,
    ];
}
