// <auto-generated />
// Generated by tools/generate_compact_cache.py; exact replacement for q = -293..324.
// Derived from integer interval constraints; do not hand-edit constants.
// Reconstruction follows the normalized major/minor method credited to
// Dougall Johnson in vitaut/zmij. See THIRD-PARTY-NOTICES.txt and
// docs/benchmark-results.md (size profiles and primary sources).
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace ZmijSharp;

internal static class CompactPow10Cache
{
    internal const int MinExponent = -293;
    internal const int MaxExponent = 324;
    private const int AnchorStart = -298;
    private const int Stride = 16;

    // ToDecimal supplies q in [-293, 323] for double and [-32, 44] for float.
    // The range proof covers all three unchecked reads; do not call with an
    // arbitrary exponent. No heap arrays or runtime expansion are required.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static void Get(int decimalExp, out ulong high, out ulong low)
    {
        unchecked
        {
            int fixupIndex = decimalExp - MinExponent;
            Debug.Assert((uint)fixupIndex < MaxExponent - MinExponent + 1U);

            int index = decimalExp - AnchorStart;
            int block = index >> 4;
            int residue = index & (Stride - 1);
            int offset = block * 2;
            ulong m = Unsafe.Add(ref MemoryMarshal.GetReference(Minor), residue);
            ref ulong anchor = ref Unsafe.Add(ref MemoryMarshal.GetReference(Anchors), offset);

            ulong lowerHigh = Math.BigMul(Unsafe.Add(ref anchor, 1), m, out ulong c0);
            ulong upperHigh = Math.BigMul(anchor, m, out ulong upperLow);
            ulong c1 = lowerHigh + upperLow;
            ulong c2 = upperHigh + (c1 < lowerHigh ? 1UL : 0UL);

            // Normalize the 192-bit product by shifting right by 63 or 64.
            ulong normalizedMask = (ulong)((long)c2 >> 63);
            high = (c2 & normalizedMask) | (((c2 << 1) | (c1 >> 63)) & ~normalizedMask);
            low = (c1 & normalizedMask) | (((c1 << 1) | (c0 >> 63)) & ~normalizedMask);

            ulong correction = (ulong)((Unsafe.Add(ref MemoryMarshal.GetReference(Fixups), fixupIndex >> 3) >> (fixupIndex & 7)) & 1);
            // The generator proves this correction never borrows from high
            // for any of the 618 entries. Do not extend the table unchecked.
            Debug.Assert(low >= correction);
            low -= correction;
        }
    }

    // 624 raw bytes.
    private static ReadOnlySpan<ulong> Anchors =>
    [
        0x85F0468293F0EB4EUL, 0x25BBF56008C58EA5UL, // q0 = -298
        0x94B3A202EB1C3F39UL, 0x7BF7D71432F3D6AAUL, // q0 = -282
        0xA5178FFF668AE0B6UL, 0x626E974DBE39A873UL, // q0 = -266
        0xB749FAED14125D36UL, 0xCEF980EC671F667CUL, // q0 = -250
        0xCB7DDCDDA26DA268UL, 0xA9942F5DCF7DFD0AUL, // q0 = -234
        0xE1EBCE4DC7F16DFBUL, 0xD3E8495912C62895UL, // q0 = -218
        0xFAD2A4B13D1B5D6CUL, 0x796B805720085F82UL, // q0 = -202
        0x8B3C113C38F9F37EUL, 0xDE83BC408DD3DD05UL, // q0 = -186
        0x9A94DD3E8CF578B9UL, 0x82BB74F8301958CEUL, // q0 = -170
        0xAB9EB47C81F5114FUL, 0x066EA92F3F326565UL, // q0 = -154
        0xBE89523386091465UL, 0xF6BBB397F1135824UL, // q0 = -138
        0xD389B47879823479UL, 0x4AFF1D108D4EC2C4UL, // q0 = -122
        0xEADAB0ABA3B2DBE5UL, 0x2B45AC74CCEA842FUL, // q0 = -106
        0x825ECC24C873782FUL, 0x8ED400668C0C28C9UL, // q0 = -90
        0x90BD77F3483BB9B9UL, 0xB1C6F22B5E6F48C3UL, // q0 = -74
        0xA0B19D2AB70E6ED6UL, 0x5B6ACEAEAE9D0EC5UL, // q0 = -58
        0xB267ED1940F1C61CUL, 0x55F038B237591ED4UL, // q0 = -42
        0xC612062576589DDAUL, 0x95364AFE032A819EUL, // q0 = -26
        0xDBE6FECEBDEDD5BEUL, 0xB573440E5A884D1CUL, // q0 = -10
        0xF424000000000000UL, 0x0000000000000000UL, // q0 = 6
        0x878678326EAC9000UL, 0x0000000000000000UL, // q0 = 22
        0x96769950B50D88F4UL, 0x1314448000000000UL, // q0 = 38
        0xA70C3C40A64E6C51UL, 0x999090B65F67D924UL, // q0 = 54
        0xB975D6B6EE39E436UL, 0xB3E2FD538E122B45UL, // q0 = 70
        0xCDE6FD5E09ABCF26UL, 0xED4C0226B55E6F87UL, // q0 = 86
        0xE498F455C38B997AUL, 0x0B6DFB9C0F956447UL, // q0 = 102
        0xFDCB4FA002162A63UL, 0x73D9732FC7C8F7F7UL, // q0 = 118
        0x8CE2529E2734BB1DUL, 0x1899E4A65F58660DUL, // q0 = 134
        0x9C69A97284B578D7UL, 0xFF2A760414536EFCUL, // q0 = 150
        0xADA72CCC20054AE9UL, 0xAF561AA79A10AE6BUL, // q0 = 166
        0xC0CB28A98FCF3C7FUL, 0x84576A1BB416A7DEUL, // q0 = 182
        0xD60B3BD56A5586F1UL, 0x8A71E223D8D3B075UL, // q0 = 198
        0xEDA2EE1C7064130CUL, 0x1162DEF06F79DF74UL, // q0 = 214
        0x83EA2B892091E44DUL, 0x934AED0AAB460433UL, // q0 = 230
        0x92746B9BE2F8552CUL, 0x32FD3CF5B4E49BB5UL, // q0 = 246
        0xA298F2C501F45F42UL, 0x8349F3BA91B47B90UL, // q0 = 262
        0xB484F9DC9641E9DAUL, 0xB1F9F660802DEDF7UL, // q0 = 278
        0xC86AB5C39FA63440UL, 0x8DD9472BF3FEFAA8UL, // q0 = 294
        0xDE81E40A034BCF4FUL, 0xF8077F7EA65E58D1UL, // q0 = 310
    ];

    // 128 raw bytes.
    private static ReadOnlySpan<ulong> Minor =>
    [
        0x8000000000000000UL, 0xA000000000000000UL, 0xC800000000000000UL, 0xFA00000000000000UL,
        0x9C40000000000000UL, 0xC350000000000000UL, 0xF424000000000000UL, 0x9896800000000000UL,
        0xBEBC200000000000UL, 0xEE6B280000000000UL, 0x9502F90000000000UL, 0xBA43B74000000000UL,
        0xE8D4A51000000000UL, 0x9184E72A00000000UL, 0xB5E620F480000000UL, 0xE35FA931A0000000UL,
    ];

    // 78 raw bytes.
    private static ReadOnlySpan<byte> Fixups =>
    [
        0x00, 0x78, 0xCF, 0x0A, 0x00, 0x18, 0x30, 0x08, 0x06, 0x7C, 0x59, 0xBF,
        0xD6, 0x18, 0x38, 0x06, 0x00, 0x18, 0x7C, 0x1E, 0x00, 0xE8, 0xEF, 0x0F,
        0x80, 0x3B, 0x88, 0x8A, 0x1F, 0xF8, 0x6D, 0x5F, 0x0B, 0xFE, 0xB4, 0xDF,
        0x1B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x11, 0x88,
        0x40, 0x00, 0x00, 0x48, 0x80, 0x38, 0xCD, 0x58, 0x01, 0xFD, 0x67, 0x0B,
        0x04, 0x08, 0x80, 0x08, 0x00, 0xA8, 0xDF, 0x1E, 0x15, 0x38, 0x00, 0xDB,
        0xB4, 0x1D, 0x00, 0x01, 0x00, 0x00,
    ];
}
