// <auto-generated />
// Binary32-only direct cache: q = -32..44, copied from Pow10Tables.
// Regenerate with tools/generate_float_full_cache.py; 77 entries = 1,232 bytes.
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace ZmijSharp;

internal static class FloatFullPow10Cache
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static void Get(int exponent, out ulong high, out ulong low)
    {
        int index = exponent + 32;
        Debug.Assert((uint)index < 77U);
        ref ulong pair = ref Unsafe.Add(ref MemoryMarshal.GetReference(Powers), index << 1);
        high = pair;
        low = Unsafe.Add(ref pair, 1);
    }

    private static ReadOnlySpan<ulong> Powers =>
    [
        0xcfb11ead453994baUL, 0x67de18eda5814af2UL, // q = -32
        0x81ceb32c4b43fcf4UL, 0x80eacf948770ced7UL, // q = -31
        0xa2425ff75e14fc31UL, 0xa1258379a94d028dUL, // q = -30
        0xcad2f7f5359a3b3eUL, 0x096ee45813a04330UL, // q = -29
        0xfd87b5f28300ca0dUL, 0x8bca9d6e188853fcUL, // q = -28
        0x9e74d1b791e07e48UL, 0x775ea264cf55347dUL, // q = -27
        0xc612062576589ddaUL, 0x95364afe032a819dUL, // q = -26
        0xf79687aed3eec551UL, 0x3a83ddbd83f52204UL, // q = -25
        0x9abe14cd44753b52UL, 0xc4926a9672793542UL, // q = -24
        0xc16d9a0095928a27UL, 0x75b7053c0f178293UL, // q = -23
        0xf1c90080baf72cb1UL, 0x5324c68b12dd6338UL, // q = -22
        0x971da05074da7beeUL, 0xd3f6fc16ebca5e03UL, // q = -21
        0xbce5086492111aeaUL, 0x88f4bb1ca6bcf584UL, // q = -20
        0xec1e4a7db69561a5UL, 0x2b31e9e3d06c32e5UL, // q = -19
        0x9392ee8e921d5d07UL, 0x3aff322e62439fcfUL, // q = -18
        0xb877aa3236a4b449UL, 0x09befeb9fad487c2UL, // q = -17
        0xe69594bec44de15bUL, 0x4c2ebe687989a9b3UL, // q = -16
        0x901d7cf73ab0acd9UL, 0x0f9d37014bf60a10UL, // q = -15
        0xb424dc35095cd80fUL, 0x538484c19ef38c94UL, // q = -14
        0xe12e13424bb40e13UL, 0x2865a5f206b06fb9UL, // q = -13
        0x8cbccc096f5088cbUL, 0xf93f87b7442e45d3UL, // q = -12
        0xafebff0bcb24aafeUL, 0xf78f69a51539d748UL, // q = -11
        0xdbe6fecebdedd5beUL, 0xb573440e5a884d1bUL, // q = -10
        0x89705f4136b4a597UL, 0x31680a88f8953030UL, // q = -9
        0xabcc77118461cefcUL, 0xfdc20d2b36ba7c3dUL, // q = -8
        0xd6bf94d5e57a42bcUL, 0x3d32907604691b4cUL, // q = -7
        0x8637bd05af6c69b5UL, 0xa63f9a49c2c1b10fUL, // q = -6
        0xa7c5ac471b478423UL, 0x0fcf80dc33721d53UL, // q = -5
        0xd1b71758e219652bUL, 0xd3c36113404ea4a8UL, // q = -4
        0x83126e978d4fdf3bUL, 0x645a1cac083126e9UL, // q = -3
        0xa3d70a3d70a3d70aUL, 0x3d70a3d70a3d70a3UL, // q = -2
        0xccccccccccccccccUL, 0xccccccccccccccccUL, // q = -1
        0x8000000000000000UL, 0x0000000000000000UL, // q = 0
        0xa000000000000000UL, 0x0000000000000000UL, // q = 1
        0xc800000000000000UL, 0x0000000000000000UL, // q = 2
        0xfa00000000000000UL, 0x0000000000000000UL, // q = 3
        0x9c40000000000000UL, 0x0000000000000000UL, // q = 4
        0xc350000000000000UL, 0x0000000000000000UL, // q = 5
        0xf424000000000000UL, 0x0000000000000000UL, // q = 6
        0x9896800000000000UL, 0x0000000000000000UL, // q = 7
        0xbebc200000000000UL, 0x0000000000000000UL, // q = 8
        0xee6b280000000000UL, 0x0000000000000000UL, // q = 9
        0x9502f90000000000UL, 0x0000000000000000UL, // q = 10
        0xba43b74000000000UL, 0x0000000000000000UL, // q = 11
        0xe8d4a51000000000UL, 0x0000000000000000UL, // q = 12
        0x9184e72a00000000UL, 0x0000000000000000UL, // q = 13
        0xb5e620f480000000UL, 0x0000000000000000UL, // q = 14
        0xe35fa931a0000000UL, 0x0000000000000000UL, // q = 15
        0x8e1bc9bf04000000UL, 0x0000000000000000UL, // q = 16
        0xb1a2bc2ec5000000UL, 0x0000000000000000UL, // q = 17
        0xde0b6b3a76400000UL, 0x0000000000000000UL, // q = 18
        0x8ac7230489e80000UL, 0x0000000000000000UL, // q = 19
        0xad78ebc5ac620000UL, 0x0000000000000000UL, // q = 20
        0xd8d726b7177a8000UL, 0x0000000000000000UL, // q = 21
        0x878678326eac9000UL, 0x0000000000000000UL, // q = 22
        0xa968163f0a57b400UL, 0x0000000000000000UL, // q = 23
        0xd3c21bcecceda100UL, 0x0000000000000000UL, // q = 24
        0x84595161401484a0UL, 0x0000000000000000UL, // q = 25
        0xa56fa5b99019a5c8UL, 0x0000000000000000UL, // q = 26
        0xcecb8f27f4200f3aUL, 0x0000000000000000UL, // q = 27
        0x813f3978f8940984UL, 0x4000000000000000UL, // q = 28
        0xa18f07d736b90be5UL, 0x5000000000000000UL, // q = 29
        0xc9f2c9cd04674edeUL, 0xa400000000000000UL, // q = 30
        0xfc6f7c4045812296UL, 0x4d00000000000000UL, // q = 31
        0x9dc5ada82b70b59dUL, 0xf020000000000000UL, // q = 32
        0xc5371912364ce305UL, 0x6c28000000000000UL, // q = 33
        0xf684df56c3e01bc6UL, 0xc732000000000000UL, // q = 34
        0x9a130b963a6c115cUL, 0x3c7f400000000000UL, // q = 35
        0xc097ce7bc90715b3UL, 0x4b9f100000000000UL, // q = 36
        0xf0bdc21abb48db20UL, 0x1e86d40000000000UL, // q = 37
        0x96769950b50d88f4UL, 0x1314448000000000UL, // q = 38
        0xbc143fa4e250eb31UL, 0x17d955a000000000UL, // q = 39
        0xeb194f8e1ae525fdUL, 0x5dcfab0800000000UL, // q = 40
        0x92efd1b8d0cf37beUL, 0x5aa1cae500000000UL, // q = 41
        0xb7abc627050305adUL, 0xf14a3d9e40000000UL, // q = 42
        0xe596b7b0c643c719UL, 0x6d9ccd05d0000000UL, // q = 43
        0x8f7e32ce7bea5c6fUL, 0xe4820023a2000000UL, // q = 44
    ];
}
