"""Generate the binary32 direct cache from the existing full Zmij table."""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/ZmijSharp/Pow10Tables.cs"
TARGET = ROOT / "src/ZmijSharp/FloatFullPow10Cache.cs"

words = re.findall(r"0x[0-9a-fA-F]{16}UL", SOURCE.read_text(encoding="utf-8"))
if len(words) != 618 * 2:
    raise SystemExit(f"Expected 1,236 full-cache words, found {len(words)}")

start = (-32 + 293) * 2
selected = words[start : start + 77 * 2]
lines = [
    "// <auto-generated />",
    "// Binary32-only direct cache: q = -32..44, copied from Pow10Tables.",
    "// Regenerate with tools/generate_float_full_cache.py; 77 entries = 1,232 bytes.",
    "using System.Diagnostics;",
    "using System.Runtime.CompilerServices;",
    "using System.Runtime.InteropServices;",
    "",
    "namespace ZmijSharp;",
    "",
    "internal static class FloatFullPow10Cache",
    "{",
    "    [MethodImpl(MethodImplOptions.AggressiveInlining)]",
    "    internal static void Get(int exponent, out ulong high, out ulong low)",
    "    {",
    "        int index = exponent + 32;",
    "        Debug.Assert((uint)index < 77U);",
    "        ref ulong pair = ref Unsafe.Add(ref MemoryMarshal.GetReference(Powers), index << 1);",
    "        high = pair;",
    "        low = Unsafe.Add(ref pair, 1);",
    "    }",
    "",
    "    private static ReadOnlySpan<ulong> Powers =>",
    "    [",
]
for index in range(77):
    high, low = selected[index * 2 : index * 2 + 2]
    lines.append(f"        {high}, {low}, // q = {index - 32}")
lines.extend(["    ];", "}"])
content = "\n".join(lines) + "\n"

if "--check" in sys.argv:
    if TARGET.read_text(encoding="utf-8") != content:
        raise SystemExit(f"Out of date: {TARGET}")
else:
    TARGET.write_text(content, encoding="utf-8", newline="\n")
