"""Generate the benchmark-only xjb64 direct cache from Zmij's full cache."""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/ZmijSharp/Pow10Tables.cs"
TARGET = ROOT / "benchmarks/XjbSharp/XjbDoubleCache.cs"

words = [int(s[:-2], 16) for s in re.findall(r"0x[0-9a-fA-F]{16}UL", SOURCE.read_text(encoding="utf-8"))]
if len(words) != 618 * 2:
    raise SystemExit(f"Expected 1,236 full-cache words, found {len(words)}")

lines = [
    "// <auto-generated />",
    "// xjb64 direct cache for q = -293..323, derived from Pow10Tables.",
    "// Generate with tools/generate_xjb_double_cache.py; benchmark-only, Apache-2.0.",
    "using System.Diagnostics;",
    "using System.Runtime.CompilerServices;",
    "using System.Runtime.InteropServices;",
    "",
    "namespace ZmijSharp;",
    "",
    "internal static class XjbDoubleCache",
    "{",
    "    [MethodImpl(MethodImplOptions.AggressiveInlining)]",
    "    internal static void Get(int exponent, out ulong high, out ulong low)",
    "    {",
    "        int index = exponent + 293;",
    "        Debug.Assert((uint)index < 617U);",
    "        ref ulong pair = ref Unsafe.Add(ref MemoryMarshal.GetReference(Powers), index << 1);",
    "        high = pair;",
    "        low = Unsafe.Add(ref pair, 1);",
    "    }",
    "",
    "    private static ReadOnlySpan<ulong> Powers =>",
    "    [",
]
for index in range(617):
    exponent = index - 293
    high, low = words[index * 2 : index * 2 + 2]
    if exponent < 0 or exponent > 55:
        low += 1
    lines.append(f"        0x{high:016x}UL, 0x{low:016x}UL, // q = {exponent}")
lines.extend(["    ];", "}"])
content = "\n".join(lines) + "\n"

if "--check" in sys.argv:
    if TARGET.read_text(encoding="utf-8") != content:
        raise SystemExit(f"Out of date: {TARGET}")
else:
    TARGET.write_text(content, encoding="utf-8", newline="\n")
