"""Generate xjb's exponent-indexed binary32 shift table for the v2 trial."""

from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
target = root / "benchmarks/XjbSharp/XjbFloatH37.cs"
values = []
for exponent in range(255):
    q = (exponent if exponent else 1) - 150
    k = (q * 1233) >> 12
    values.append(q + ((-k * 1701 - 1701) >> 9) + 37)
values.append(0)  # Exponent 255 is nonfinite and bypasses the table.
if not all(33 <= value <= 36 for value in values[:-1]):
    raise SystemExit("Unexpected binary32 shift")

lines = [
    "// <auto-generated />",
    "// xjb v2 binary32 h + 37 lookup; exponent 255 is unused.",
    "// Generated by tools/generate_xjb_float_h37.py; Apache-2.0 notice applies.",
    "using System.Diagnostics;",
    "using System.Runtime.CompilerServices;",
    "using System.Runtime.InteropServices;",
    "",
    "namespace ZmijSharp;",
    "",
    "internal static class XjbFloatH37",
    "{",
    "    [MethodImpl(MethodImplOptions.AggressiveInlining)]",
    "    internal static int Get(int exponent)",
    "    {",
    "        Debug.Assert((uint)exponent < 255U);",
    "        return Unsafe.Add(ref MemoryMarshal.GetReference(Values), exponent);",
    "    }",
    "",
    "    private static ReadOnlySpan<byte> Values =>",
    "    [",
]
for i in range(0, len(values), 16):
    lines.append("        " + ", ".join(map(str, values[i:i + 16])) + ",")
lines.extend(["    ];", "}"])
content = "\n".join(lines) + "\n"
if "--check" in sys.argv:
    if target.read_text(encoding="utf-8") != content:
        raise SystemExit(f"Out of date: {target}")
else:
    target.write_text(content, encoding="utf-8", newline="\n")
